"""added modified path

Revision ID: 01b36c051be7
Revises: 4fe6c2d08a65
Create Date: 2019-07-12 15:49:16.518865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b36c051be7'
down_revision = '4fe6c2d08a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pics', sa.Column('path_modified', sa.VARCHAR(length=250), nullable=True))
    op.create_unique_constraint(None, 'pics', ['path_modified'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pics', type_='unique')
    op.drop_column('pics', 'path_modified')
    # ### end Alembic commands ###
