"""hey

Revision ID: 4fe6c2d08a65
Revises: 0e6541dbf0ad
Create Date: 2019-07-01 21:40:14.535322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fe6c2d08a65'
down_revision = '0e6541dbf0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pics', sa.Column('date_doc', sa.DateTime(), nullable=True))
    op.add_column('pics', sa.Column('date_photo', sa.DateTime(), nullable=False))
    op.add_column('pics', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('pics', sa.Column('transcript', sa.Text(), nullable=True))
    op.drop_column('pics', 'date')
    op.drop_column('pics', 'ocr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pics', sa.Column('ocr', mysql.TEXT(), nullable=True))
    op.add_column('pics', sa.Column('date', mysql.DATETIME(), nullable=False))
    op.drop_column('pics', 'transcript')
    op.drop_column('pics', 'page_number')
    op.drop_column('pics', 'date_photo')
    op.drop_column('pics', 'date_doc')
    # ### end Alembic commands ###
