"""hey

Revision ID: 6fa5c01d0102
Revises: 
Create Date: 2019-06-12 15:35:03.903985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa5c01d0102'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('path', sa.VARCHAR(length=250), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('added', sa.DateTime(), nullable=False),
    sa.Column('ocr', sa.Text(), nullable=True),
    sa.Column('tagged', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('path')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_hierarchy',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'node_id')
    )
    op.create_table('tag_identifier',
    sa.Column('pic_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pic_id'], ['pics.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.create_table('thumbnails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pic_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('path', sa.VARCHAR(length=250), nullable=False),
    sa.ForeignKeyConstraint(['pic_id'], ['pics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thumbnails')
    op.drop_table('tag_identifier')
    op.drop_table('tag_hierarchy')
    op.drop_table('tags')
    op.drop_table('pics')
    # ### end Alembic commands ###
