"""add folder and hiddden

Revision ID: be227523f328
Revises: dc8e9d72b993
Create Date: 2019-06-20 20:56:26.769811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be227523f328'
down_revision = 'dc8e9d72b993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('hidden', sa.Boolean(), nullable=True))
    op.add_column('tags', sa.Column('isFolder', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'isFolder')
    op.drop_column('tags', 'hidden')
    # ### end Alembic commands ###
