"""added columns to pic

Revision ID: ce7e4eed0272
Revises: a36d9592c392
Create Date: 2019-06-18 16:03:43.355601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce7e4eed0272'
down_revision = 'a36d9592c392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pics', sa.Column('author', sa.String(), nullable=True))
    op.add_column('pics', sa.Column('box', sa.String(), nullable=True))
    op.add_column('pics', sa.Column('collection', sa.String(), nullable=True))
    op.add_column('pics', sa.Column('title', sa.String(length=140), nullable=True))
    op.drop_index('name', table_name='pics')
    op.create_unique_constraint(None, 'pics', ['title'])
    op.drop_column('pics', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pics', sa.Column('name', mysql.VARCHAR(length=140), nullable=True))
    op.drop_constraint(None, 'pics', type_='unique')
    op.create_index('name', 'pics', ['name'], unique=True)
    op.drop_column('pics', 'title')
    op.drop_column('pics', 'collection')
    op.drop_column('pics', 'box')
    op.drop_column('pics', 'author')
    # ### end Alembic commands ###
