"""deunique

Revision ID: dc8e9d72b993
Revises: 5cadf9a9a8fc
Create Date: 2019-06-18 20:23:59.304770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8e9d72b993'
down_revision = '5cadf9a9a8fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title', table_name='pics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title', 'pics', ['title'], unique=True)
    # ### end Alembic commands ###
